import type { Task, AppMode, Course } from '../types';
import { supabase } from '../supabaseClient';
import { format, isBefore, startOfDay, parseISO } from 'date-fns';

const MODE_KEY = 'daily-flow-mode';
const COURSES_KEY = 'daily-flow-courses-v2';

// Default courses
const DEFAULT_COURSES: Course[] = [
    { id: 'course1', name: 'Pak Studies', color: '#84A98C' },
    { id: 'course2', name: 'Maths', color: '#52796F' },
    { id: 'course3', name: 'Computer Vision', color: '#D6CCC2' },
    { id: 'course4', name: 'History', color: '#CAD2C5' },
    { id: 'course5', name: 'Mass Comm', color: '#354F52' }
];

// Mode management
export const getMode = (): AppMode => {
    const stored = localStorage.getItem(MODE_KEY);
    return (stored as AppMode) || 'personal';
};

export const saveMode = (mode: AppMode) => {
    localStorage.setItem(MODE_KEY, mode);
};

// Course management
export const getCourses = (): Course[] => {
    const stored = localStorage.getItem(COURSES_KEY);
    return stored ? JSON.parse(stored) : DEFAULT_COURSES;
};

export const saveCourses = (courses: Course[]) => {
    localStorage.setItem(COURSES_KEY, JSON.stringify(courses));
};

// Task management - REMOTE (Supabase)

export const fetchTasks = async (): Promise<Task[]> => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];

    const { data, error } = await supabase
        .from('tasks')
        .select('*');

    if (error) {
        console.error('Error fetching tasks:', error);
        return [];
    }

    // Map DB fields to Task type if needed (assuming 1:1 match for simplicity, 
    // but DB usually snake_case, JS camelCase. I need to handle this).
    // Supabase returns keys as they are in DB. 
    // If I created table with snake_case (e.g. course_id), I need to map.
    // My previous plan SQL used snake_case.

    return (data || []).map((row: any) => ({
        id: row.id,
        title: row.title,
        date: row.date,
        deadline: row.deadline,
        courseId: row.course_id,
        completed: row.completed,
        createdAt: row.created_at,
        completedAt: row.completed_at
    }));
};

export const addTask = async (task: Task): Promise<Task | null> => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;

    const dbTask = {
        // id is generated by default if not provided, but here we might prefer letting DB gen it
        // OR we gen it client side. Let's let DB gen it, but if Task has ID, we use it?
        // Usually UUID is generated by DB.
        // Let's assume we pass the full task object.
        // If task.id is temp, we might ignore it? 
        // Actually best to let DB handle ID.
        title: task.title,
        date: task.date,
        deadline: task.deadline,
        course_id: task.courseId,
        completed: task.completed,
        created_at: task.createdAt,
        completed_at: task.completedAt,
        user_id: user.id
    };

    const { data, error } = await supabase
        .from('tasks')
        .insert([dbTask])
        .select()
        .single();

    if (error) {
        console.error('Error adding task:', error);
        return null;
    }

    return {
        id: data.id,
        title: data.title,
        date: data.date,
        deadline: data.deadline,
        courseId: data.course_id,
        completed: data.completed,
        createdAt: data.created_at,
        completedAt: data.completed_at
    };
};

export const updateTask = async (task: Task): Promise<Task | null> => {
    const dbTask = {
        title: task.title,
        date: task.date,
        deadline: task.deadline,
        course_id: task.courseId,
        completed: task.completed,
        completed_at: task.completedAt
    };

    const { data, error } = await supabase
        .from('tasks')
        .update(dbTask)
        .eq('id', task.id)
        .select()
        .single();

    if (error) {
        console.error('Error updating task:', error);
        return null;
    }

    return {
        id: data.id,
        title: data.title,
        date: data.date,
        deadline: data.deadline,
        courseId: data.course_id,
        completed: data.completed,
        createdAt: data.created_at,
        completedAt: data.completed_at
    };
};

export const deleteTask = async (taskId: string): Promise<boolean> => {
    const { error } = await supabase
        .from('tasks')
        .delete()
        .eq('id', taskId);

    if (error) {
        console.error('Error deleting task:', error);
        return false;
    }
    return true;
};

// Carry over logic - now needs to be async or handled by caller
export const processCarryOver = async (tasks: Task[]): Promise<boolean> => {
    const today = format(new Date(), 'yyyy-MM-dd');
    const todayDate = startOfDay(new Date());
    let hasChanges = false;

    const updates = tasks.map(async (task) => {
        if (!task.courseId && !task.completed && isBefore(parseISO(task.date), todayDate)) {
            hasChanges = true;
            // Update remotely
            const updatedTask = { ...task, date: today };
            await updateTask(updatedTask);
        }
    });

    await Promise.all(updates);
    return hasChanges;
};

